### ISSUE TITLE
Issue generating GC correction file

### ISSUE THREAD

**Issue by dsampath31** [cancerit/ascatNgs#103]
Hi,

I am trying to run WES tumor BAMs through ASCAT. So far, I have used sarek and ascat documentation to create BAF and logR inputs. I have issues in creating .gc file. I am using 1000G VCF and the script GCfilecreation.sh complains on bedtools nuc step to generate the output. Could you possibly help with this? or is there a .gc file somewhere for GRCh38 that I could use?

Thanks

**Comment by keiranmraine** [comment]
Although you have closed this I will reiterate the note at the top of the README.  WES (aka WXS) is not supported via this set of wrapper tools, only WGS.
