### ISSUE TITLE
Reference files for ascatNGS

### ISSUE THREAD

**Issue by umasaxena** [cancerit/ascatNgs#106]
This link doesnt seem to work any more - ftp://ftp.sanger.ac.uk/pub/cancer/support-files/CPIB/ascatNgs/Human/GRCh37/

Is there an alternative to get the supporting files ?

Thanks

**Comment by AndyMenzies** [comment]
Which browser are you using?  A recent update to chrome may have disabled ftp links.  Using Firefox it works fine.

**Comment by umasaxena** [comment]
Was using Chrom/Safari/Edge - even with enabling ftp links in the browser setting, none of them work

Currently installed and using firefox - (Hope to keep trying)

![Screen Shot 2021-04-23 at 8 26 29 AM](https://user-images.githubusercontent.com/1199924/115870706-9bc76c00-a40d-11eb-811a-6bc45a7a233c.png)

**Comment by umasaxena** [comment]
Btw is there an alternative to getting this file perhaps through git ?

**Comment by keiranmraine** [comment]
Please use an actual ftp client:

```bash
$ ftp -p ftp.sanger.ac.uk
Connected to ftp-sanger-ext.sanger.ac.uk.
220 ProFTPD 1.3.5a Server (WTSI Public FTP Server) [::ffff:193.62.203.115]
Name (ftp.sanger.ac.uk:XXX): anonymous
331 Anonymous login ok, send your complete email address as your password
Password:
230 Anonymous access granted, restrictions apply
Remote system type is UNIX.
Using binary mode to transfer files.
ftp> cd pub/cancer/support-files/CPIB/ascatNgs/Human/GRCh37/
250 CWD command successful
ftp> ls
227 Entering Passive Mode (193,62,203,115,128,136).
150 Opening ASCII mode data connection for file list
drwxrwxr-x   2 ftp      ftp            95 Jun 14  2016 legacy
-rwxrwxr-x   1 ftp      ftp           356 Jun 14  2016 README.txt
-rwxrwxr-x   1 ftp      ftp      67091685 Jun 14  2016 reference.tar.gz
-rwxrwxr-x   1 ftp      ftp            51 Jun 17  2016 reference.tar.gz.md5
226 Transfer complete
```

**Comment by umasaxena** [comment]
Worked, many thanks
