### ISSUE TITLE
output documentation and annotating

### ISSUE THREAD

**Issue by umasaxena** [cancerit/ascatNgs#107]
Would you be able to direct me to any documentation that elaborates ascatNGS output and also any recommendations for annotating the output with gene ID. Thanks

**Comment by keiranmraine** [comment]
Please see the [Wiki](https://github.com/cancerit/ascatNgs/wiki) which includes links to the protocols paper, as well as the README which has links to the GitHub of the [core ASCAT-R](https://github.com/cancerit/ascatNgs#ascat-core-algorithm) algorithm also.
