### ISSUE TITLE
Usage example

### ISSUE THREAD

**Issue by arpanda** [cancerit/ascatNgs#108]
Hi, 
I was looking for some usage  example(or steps) for running ascatNGS on Whole exome data. 

Any source?

Thanks
Arijit

**Comment by keiranmraine** [comment]
As stated in the [readme](https://github.com/cancerit/ascatNgs/blob/dev/README.md):

> We do not offer support for WXS analysis, please contact the authors of ASCAT [here](https://www.crick.ac.uk/peter-van-loo/software/ASCAT).
