### ISSUE TITLE
Resolution of segments called by ascatNGS

### ISSUE THREAD

**Issue by hannanw** [cancerit/ascatNgs#110]
Hi,

I have a question regarding the output from ascatNGS, what is the resolution of the segments that can be detected in a WGS sample? In the case of SNP6 arrays, there is the penalty parameter that can be optimized to control for the smallest segment detected. Is there a similar parameter for ASCATngs and if so what is the threshold that can be used to filter out noise from actual segments? Thanks!

Warmest regards,
Hannan

**Comment by AndyMenzies** [comment]
Hi Hannan

We are not the original authors of ASCAT, we wrote and maintain this helper project to make ASCAT easier to run over WGS data.  Any questions you have over concerning the core algorithm are better directed to the original authors, the Van Loo Lab at the Crick Institute.

https://www.crick.ac.uk/research/labs/peter-van-loo/software

Andy

**Comment by hannanw** [comment]
Hi Andy,

I tried asking on the original ASCAT github, they directed me here. If I understand correctly, ASCAT currently can only be run on microarrays (requiring LRR and BAF as inputs). For this project is the WGS input converted to LRR and BAF for ASCAT input and is being run on the default parameters for base ASCAT? Thanks!

Warmest regards,
Hannan

**Comment by AndyMenzies** [comment]
Hi Hannan

Both the method for SNP GC corrections and the conversion from allele counts to logR and BAF were provided to us by the Van Loo team. [See runAscat.R](https://github.com/cancerit/ascatNgs/blob/dev/perl/share/ascat/runASCAT.R)

What we do know is that the resolution of the ASCAT segments can be influenced by the distance between the SNPs in your Panel, the more SNPs you have and the closer they are together the better the resolution.  We don't have any specific data quality settings we pass through to ASCAT, so I assume its running on the defaults.  What can be useful is in the allele count step, if you ensure you only count high quality bases you can filter out much of the noise before it's passed through to ASCAT.

Is this helpful?  We don't have many R programmers in the support team so what ASCAT is doing in the core of its algorithm is not very well understood.

Andy

**Comment by hannanw** [comment]
Hi Andy,

Thanks for that, I agree it seems like it is running on the default penalty parameters for `ascat.aspcf`. Thanks for clearing that up and for the suggestion about only counting high quality bases.

Warmest regards,
Hannan
