### ISSUE TITLE
Using ASCATngs in a tumour-only mode

### ISSUE THREAD

**Issue by samhitapn** [cancerit/ascatNgs#116]
Can I use ascatngs in a tumour-only mode? If not, what is your suggestion to use it only with the tumour data/ BAMs?

**Comment by AndyMenzies** [comment]
Hi

ascatNgs is specifically designed to run over tumour/normal sample pairs.  It is not possible to run it over a single sample alone.

We typically have matched tumour/normal pairs for our data so our experience with single sample algorithms is extremely limited.  You could try [Ginkgo](https://github.com/robertaboukhalil/ginkgo) or [HMMcopy](https://bioconductor.org/packages/release/bioc/html/HMMcopy.html) but I don't know if they would be a food fit for your purpose.

**Comment by samhitapn** [comment]
Thank you.

Can I then alternatively use the original ASCAT instead by simply providing the BAF and the logR values generated elsewhere for a selected list of SNP locations? For NGS data.

Samhita

**Comment by AndyMenzies** [comment]
Technically yes, but only if you really know what you are doing.

Under the hood ASCAT expects normal cells to contaminate the tumour sample.  It uses the divergence in the snp profiles of the two samples to calculate the proportion of mutated dna in the tumour.  From there it tries to subtract normal data from the tumour so it can present a copy number profile of only the aberrant cell fraction.

If your normal data doesn't come from the same individual or is from an insilico simulation there will be a much greater distance between in the 2 snp profiles than expected, and the normal subtraction is likely to give you a misleading answer.
