### ISSUE TITLE
fail on CN_to_VCF step

### ISSUE THREAD

**Issue by alkodsi** [cancerit/ascatNgs#26]
ascatNgs fails on CN_to_VCF at the end of the run with the following error:
"/usr/bin/perl /opt/share/ascatNgs/bin/CN_to_VCF.pl -o xx.copynumber.caveman.vcf -r/human_g1k_v37.fasta -i tumor.copynumber.caveman.csv -sbm tumor.bam -sbw normal.bam" unexpectedly returned exit value 1 at (eval 319) line 13.
 at /opt/share/ascatNgs/lib/perl5/PCAP/Threaded.pm line 207

running the command gives:
ERROR: rs|reference-species must be defined.

If species defined by -rs, it will complain about assembly and if assembly defined, it will complain about platform.

My bam header looks like this
@RG     ID:1    PL:Illumina     PU:machine1     LB:library1     SM:tumor
@PG     ID:bwa  PN:bwa  VN:0.5.9-r16

I don't need the VCF output, I just want the run to complete successfully.

**Comment by keiranmraine** [comment]
Specify species, assembly and platform.  It's a minor oversight in the code.  FYI 'Illumina' is not technically valid according to the SAM/BAM specification it should be 'ILLUMINA'

**Comment by alkodsi** [comment]
Thanks. these parameters cannot be passed to ascat.pl. So what should I do?

**Comment by alkodsi** [comment]
sorry, I just found the parameters. Will try that

**Comment by alkodsi** [comment]
After trying passing all the parameters, some samples finished successfully, some returned error code 25 without any further details and other failed at the indexing step (tabix) with error unsorted input file.

**Comment by alkodsi** [comment]
It turns out that my custom probes have position in chrY and ascat has a hardcoded segment in chromosome Y appended to the segmentation which in some cases disturbs the sorting. I removed chrY probes and it worked.
