### ISSUE TITLE
Usage documentation for ASCAT NGS

### ISSUE THREAD

**Issue by blecuacp** [cancerit/ascatNgs#31]
Dear developers,

I am a research associate at Sloan Kettering Cancer Center in NYC. I am building up a pipeline with different softwares for cancer exome data  and downstream analysis and would be very interested in including ASCAT NGS.

Would you by any chance have available somewhere some sort of manual  on how to install and specifically on how to use ASCAT NGS?

I took a look at the ASCAT official webpage and I could not see any reference yet to ASCAT NGS. I then contacted someone managing the webpage and they prompted me to ask you.

I would highly appreciate your valuable help.

Many thanks in advance for your kind attention,

Yours sincerely,

Pedro.

**Comment by Hbm3085** [comment]
Hi 

I have the same question as Pedro. Is there any information on how to use ASCAT-NGS.
As a longtime ASCAT user it would be nice to run similar analysis on NGS data.

Many thanks,
Hasan

**Comment by keiranmraine** [comment]
Hi,

ascatNgs has command line help which should provide you with the bulk of the information that you require.

````
$ ascat.pl -h
Usage:
    ascat.pl [options]

      Please defined as many of the parameters as possible

      Required parameters

        -outdir       -o    Folder to output result to.
        -tumour       -t    Tumour BAM/CRAM file
        -normal       -n    Normal BAM/CRAM file
        -reference    -r    Reference fasta
        -snp_loci     -s    Snp locus file
        -snp_pos      -sp   Snp position file
        -snp_gc       -sg   Snp GC correction file
        -gender       -g    Sample gender (XX, XY, L)
                              For XX/XY see '-gc'
                              When 'L' see '-l'

      Targeted processing (further detail under OPTIONS):
        -process      -p    Only process this step then exit, optionally set -index
        -index        -i    Optionally restrict '-p' to single job
        -limit        -x    Specifying 2 will balance processing between '-i 1 & 2'
                            Must be paired with '-p allele_count'

      Optional parameters
        -genderChr    -gc   Specify the 'Male' sex chromosome: X,chrX...
        -species      -rs   Reference species [BAM HEADER]
        -assembly     -ra   Reference assembly [BAM HEADER]
        -protocol     -pr   Sequencing protocol (e.g. WGS, WXS)
        -platform     -pl   Seqeuncing platform [BAM HEADER]
        -minbasequal  -q    Minimum base quality required before allele is used. [20]
        -cpus         -c    Number of cores to use. [1]
                            - recommend max 2 during 'input' process.
        -locus        -l    Using a list of loci, default when '-L' [share/gender/GRCh37d5_Y.loci]
                            - these are loci that will not present at all in a female sample
        -force        -f    Force completion - solution not possible
                            - adding this will result in successful completion of analysis even
                              when ASCAT can't generate a solution.  A default copynumber of 5/2
                              (tumour/normal) and contamination of 30% will be set along with a
                              comment in '*.samplestatistics.csv' to indicate this has occurred.
        -purity       -pu   Purity (rho) setting for manual setting of sunrise plot location
        -ploidy       -pi   Ploidy (psi) setting for manual setting of sunrise plot location
        -noclean      -nc   Finalise results but don't clean up the tmp directory.
                            - Useful when including a manual check and restarting ascat with new pu and pi params.

      Other
        -help         -h    Brief help message
        -man          -m    Full documentation.
        -version      -v    Ascat version number
````

A set of reference files for GRCh37 (`-snp_*` options) are [attached](https://github.com/cancerit/ascatNgs/releases/tag/v1.5.2) to one of the earlier releases.

Details of how to build a custom set of reference files are detailed in the [wiki](https://github.com/cancerit/ascatNgs/wiki).

Please be aware that **_this tool is not suitable for exome analysis_**.

A protocols paper similar to the [cgpPindel](http://onlinelibrary.wiley.com/doi/10.1002/0471250953.bi1507s52/full) and [VAGrENT](http://onlinelibrary.wiley.com/doi/10.1002/0471250953.bi1508s52/full) papers is currently being prepared.

Kind regards,
Keiran
