### ISSUE TITLE
Expected ASCAT output file missing: TUMORNAME.aberrationreliability.png

### ISSUE THREAD

**Issue by komalsrathi** [cancerit/ascatNgs#38]
Hi,

I am running ascatNgs v1.5.2 for whole-exome data. At the second step i.e. -p ascat, sometimes the **.aberrationreliability.png** file is not created because of which finalise fails. Do you have a work around for this issue?

Thanks a lot,
Komal

**Comment by keiranmraine** [comment]
Although there is an option '-f' to force completion you will not get a useful profile from exome analysis.

**Comment by komalsrathi** [comment]
Why does it not create the abberation reliability plot for some samples?

On Wednesday, March 23, 2016, Keiran Raine <notifications@github.com> wrote:

> Although there is an option '-f' to force completion you will not get a
> useful profile from exome analysis.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/cancerit/ascatNgs/issues/38#issuecomment-200259667>
>


-- 
*Komal S Rathi* | Bioinformatics Engineer II, Memorial Sloan Kettering
Cancer Center | rathik@mskcc.org | komalr@mail.med.upenn.edu |
krathi1@jhu.edu <krathi1@live.johnshopkins.edu>
