### ISSUE TITLE
Understanding Ascat output

### ISSUE THREAD

**Issue by komalsrathi** [cancerit/ascatNgs#39]
Hello,

We are using ascatNgs 1.7.2 to analyze some whole-exome datasets. We are getting unexpected outputs for most of our samples. Here is the output for one of the samples:

![w0006013f aspcf](https://cloud.githubusercontent.com/assets/7000615/14048001/d8a6acdc-f281-11e5-9275-702acae52eff.png)

![w0006013f rawprofile](https://cloud.githubusercontent.com/assets/7000615/14048004/dc41ee42-f281-11e5-8632-ef94880736be.png)

Can you tell me if there could be something wrong with the input files or whether it is common to see such an output?

**Comment by keiranmraine** [comment]
As I indicated in #38 ASCAT is will not work on whole-exome, it is only expected to give a usable result for wholegenome analysis.
