### ISSUE TITLE
samplename not found

### ISSUE THREAD

**Issue by Hbm3085** [cancerit/ascatNgs#44]
Hi,

I am getting the following error while running ascat.pl :

```
WARN: Failed to find samplename in RG headers of /<path>/*.bam
Use of uninitialized value $sample in substitution (s///) at /apps/ascatngs/2.0.1/lib/perl5/Sanger/CGP/Ascat/Implement.pm line 280.
```

Is there a workaround this?

Many thanks,
Hasan

**Comment by keiranmraine** [comment]
You need to have well formed BAM files.  You can add a readgroup header to a BAM with samtools.
