### ISSUE TITLE
1000 genome SNP panel generation

### ISSUE THREAD

**Issue by mjz1** [cancerit/ascatNgs#50]
The code snippet intended to create the 1000g SNP panel:

> $ export TG_DATA=ftp://ftp.ensembl.org/pub/grch37/release-83/variation/vcf/homo_sapiens/1000GENOMES-phase_3.vcf.gz
> $ curl -sSL $TG_DATA | zgrep -F 'E_Multiple_observations' | grep -F 'TSA=SNV' |\
>  perl -ane '\
>  next if($F[0] !~ m/^\d+$/ && $F[0] !~ m/^[XY]$/); \
>  next if($F[0] eq $l_c && $F[1]-1000 < $l_p); \
>  $F[7]=~m/MAF=([^;]+)/; next if($1 < 0.05); \
>  printf "%s\t%s\t%d\n", $F[2],$F[0],$F[1]; \
>  $l_c=$F[0]; $l_p=$F[1]; \
>  ' > SnpPositions_GRCh37_1000g.tsv

 gives the error:

> Can't modify single ref constructor in scalar assignment at -e line 6, near "];"
> syntax error at -e line 7, at EOF
> Execution of -e aborted due to compilation errors.

**Comment by keiranmraine** [comment]
Thanks for reporting this.  For some reason removing one of the escaped line feeds fixes this:

```
curl -sSL $TG_DATA | zgrep -F 'E_Multiple_observations' | grep -F 'TSA=SNV' |\
 perl -ane '\
 next if($F[0] !~ m/^\d+$/ && $F[0] !~ m/^[XY]$/); \
 next if($F[0] eq $l_c && $F[1]-1000 < $l_p); \
 $F[7]=~m/MAF=([^;]+)/; next if($1 < 0.05); \
 printf "%s\t%s\t%d\n", $F[2],$F[0],$F[1]; $l_c=$F[0]; $l_p=$F[1];' \
 > SnpPositions_GRCh37_1000g.tsv
```

I've updated the docs.  Thanks,

**Comment by mjz1** [comment]
Now this command is giving me an empty output file.

**Comment by MimoriK** [comment]
I have the same question, an empty output file.

**Comment by keiranmraine** [comment]
Removing the line feeds from the perl appears to resolve this, I don't know why they are having an impact:

```
curl -sSL $TG_DATA | zgrep -F 'E_Multiple_observations' | grep -F 'TSA=SNV' | \
perl -ane 'next if($F[0] !~ m/^\d+$/ && $F[0] !~ m/^[XY]$/); next if($F[0] eq $l_c && $F[1]-1000 < $l_p); $F[7]=~m/MAF=([^;]+)/; next if($1 < 0.05); printf "%s\t%s\t%d\n", $F[2],$F[0],$F[1]; $l_c=$F[0]; $l_p=$F[1];'
```
