### ISSUE TITLE
How to make ASCAT input files

### ISSUE THREAD

**Issue by rkumar87** [cancerit/ascatNgs#58]
I am very new to ASCAT. I have WGS sequencing data. Can you please tell me how to create ASCAT inputs (BAF and LogR files) from WGS data. What all i need to know or where i can find it?

Thanks

**Comment by keiranmraine** [comment]
The ascat.pl script handles the generation of the relevant files for the core ASCAT algorithm from a pair of Tumour/Normal BAM files:

https://github.com/cancerit/ascatNgs/wiki/Basic-usage

Please see the rest of the wiki too:

https://github.com/cancerit/ascatNgs/wiki
