### ISSUE TITLE
Running ascatNGS without matched normal data

### ISSUE THREAD

**Issue by makarov-mskcc** [cancerit/ascatNgs#62]
Hello developers,
I'd like to apply ascatNGS to the cell line sample. I wonder if it is possible to run ascatNGS without matching normal bam file, in the same was as its microarray counterpart https://www.crick.ac.uk/peter-van-loo/software/ASCAT

Thank you
Vlad

**Comment by keiranmraine** [comment]
We don't support this use case under NGS datasets.
