### ISSUE TITLE
allele_count from ascatNgs are all zeros

### ISSUE THREAD

**Issue by freya666** [cancerit/ascatNgs#64]
Hello guys,

I got a problem in running ascatNgs (version 4.0.0). 

We used tumor sample BAM file and normal sample BAM file as inputs as the program asks. Also, according to this page (https://github.com/cancerit/ascatNgs/wiki/Mouse-reference-files-from-Mouse-Genome-Project-VCFs), we produced "Snp GC correction file". We used the following command to run the program:
ascat.pl -outdir ./result/ -tumour tumor.bam -normal normal.bam -reference mm10.fa -snp_gc SnpGcCorrections.tsv -protocol WGS -gender XY -genderChr Y -species GRCm38 -assembly GRCm38.p3 -platform Illumina HiSeq 2500 -cpus 2 -force  -noclean 

But the program aborted automatically, and I noticed the result (allele_count/*.allct) from program are all zeros, as shown below:
 1 #CHR    POS     Count_A Count_C Count_G Count_T Good_depth
 2 7       3255367 0       0       0       0       0
 3 7       3475891 0       0       0       0       0
 4 7       3476046 0       0       0       0       0
 5 7       3478293 0       0       0       0       0
 6 7       3480843 0       0       0       0       0
 7 7       3482833 0       0       0       0       0
 8 7       3485157 0       0       0       0       0
 9 7       3486183 0       0       0       0       0
10 7       3489356 0       0       0       0       0

I'm not sure why I got result like this and I don't know where the problem is. Could anyone help me with this issue? Thanks in advance.

Best,

Freya

**Comment by keiranmraine** [comment]
As the reference files were built for a reference without the 'chr' prefix you may find just rebuilding the reference file with the chr prefix will resolve this.

Please note that this is untested and we will look into this soon.  There may be limitations in the R code I am unaware of as I do not control this portion of the codebase.

**Comment by keiranmraine** [comment]
We have confirmed that updating the `SnpGcCorrections.tsv` file to have chr prefix on the contig names will resolve this issue.

We will consider detecting this issue, however this is unlikely as reference files should be correlated with your genome build.  Wiki documentation will be updated to highlight this
