### ISSUE TITLE
Incomplete output running ascat.pl

### ISSUE THREAD

**Issue by yuranymoreno** [cancerit/ascatNgs#67]
Dear all, 

I am having troubles running ascat.pl. This was installed with all the tools offered by the dockstore-cgpwgs, which was installed as a singularity container in the supercomputer of my university. I am using the test data offered in your website along with my own data. Currently, I have run bas_stats and compareBamGenotypes.pl. Those tools worked perfectly fine.

However, I was running the ascat.pl with the required parameters as follows: 

module load brass
singularity exec --bind /scratch /local/software/brass/source/brass2.img ascat.pl -o /home/lym1e14/YURANY/Bioinformatic_tools/test_data/test_1/ascat/output -t /home/lym1e14/YURANY/Bioinformatic_tools/test_data/data/cell-line/HCC1143_BL.bam -n /home/lym1e14/YURANY/Bioinformatic_tools/test_data/data/cell-line/HCC1143.bam -r /home/lym1e14/YURANY/Bioinformatic_tools/test_data/cgp-test/reference_files/genome.fa -sg /home/lym1e14/YURANY/Bioinformatic_tools/test_data/cgp-test/reference_files/ascat/SnpGcCorrections.tsv -sp /home/lym1e14/YURANY/Bioinformatic_tools/test_data/cgp-test/reference_files/ascat/SnpPositions.tsv -s /home/lym1e14/YURANY/Bioinformatic_tools/test_data/cgp-test/reference_files/ascat/SnpLocus.tsv -q 20 -g L -rs HUMAN -ra GRCh37 -pr WGS -pl ILLUMINA -c 8 

I got the tmpAcat with the following directories and files:
0.normal_gender.tsv  SnpGcCorrections.tsv  SnpPositions.tsv  allele_count  ascat  logs  progress

In ascat, there are the files of the counts for the normal and tumour bam files. In progress, there were Sanger_CGP_Ascat_Implement_allele_count.XX (XX=1 to 44), but there are empty. In logs, all the .out files are empty. 

At the end, I got the following message: 

"/usr/bin/time /scratch/EXOME_DATA/YURANY/Bioinformatic_tools/test_data/test_1/ascat/output/tmpAscat/logs/Sanger_CGP_Ascat_Implement_ascat.0.sh 1> /scratch/EXOME_DATA/YURANY/Bioinformatic_tools/test_data/test_1/ascat/output/tmpAscat/logs/Sanger_CGP_Ascat_Implement_ascat.0.out 2> /scratch/EXOME_DATA/YURANY/Bioinformatic_tools/test_data/test_1/ascat/output/tmpAscat/logs/Sanger_CGP_Ascat_Implement_ascat.0.err" unexpectedly returned exit value 1 at /opt/wtsi-cgp/lib/perl5/PCAP/Threaded.pm line 263.
 at /opt/wtsi-cgp/lib/perl5/PCAP/Threaded.pm line 261

I though I have to invoke R within the container and I tried a couple of options without a solution. 

I would be really grateful if you can help to understand the reason of the failure with this command. 

Many thanks, 

Yurany

**Comment by yuranymoreno** [comment]
Hi all, 

This is the error message of Sanger_CGP_Ascat_Implement_ascat.0.err:

+ cut -f 1-3 /scratch/EXOME_DATA/YURANY/Bioinformatic_tools/test_data/test_1/ascat/output/tmpAscat/SnpGcCorrections.tsv
+ cd /scratch/EXOME_DATA/YURANY/Bioinformatic_tools/test_data/test_1/ascat/output/tmpAscat/ascat
+ /opt/wtsi-cgp/bin/Rscript /opt/wtsi-cgp/lib/perl5/auto/share/module/Sanger-CGP-Ascat-Implement/ascat/runASCAT.R /opt/wtsi-cgp/lib/perl5/auto/share/module/Sanger-CGP-Ascat-Implement/ascat /scratch/EXOME_DATA/YURANY/Bioinformatic_tools/test_data/test_1/ascat/output/tmpAscat/SnpPositions.tsv /scratch/EXOME_DATA/YURANY/Bioinformatic_tools/test_data/test_1/ascat/output/tmpAscat/SnpGcCorrections.tsv HCC1143 HCC1143.count HCC1143_BL HCC1143_BL.count XX 24 /scratch/EXOME_DATA/YURANY/Bioinformatic_tools/test_data/test_1/ascat/output/tmpAscat/ascat/HCC1143.Rdata
Error in `row.names<-.data.frame`(`*tmp*`, value = value) :
  duplicate 'row.names' are not allowed
Calls: rownames<- -> row.names<- -> row.names<-.data.frame
In addition: Warning message:
non-unique values when setting 'row.names': '10000159076', '10001443180', '10001464892', '10001580662', '10002969047', '10003714170', '10004604986', '10005716858', '10006222744', '10007144174', '10007615195', '10008597988', '10008638235', '10008711757', '10008719519', '10008851426', '10009166345', '10010104492', '10010340044', '10010514599', '10010801161', '10013103202', '10013411415', '10013685551', '10013875720', '10016305792', '10016395866', '10017260290', '10017591228', '10018459282', '10018906507', '10018984666', '10019342086', '10020000428', '10021349368', '10023396508', '10023818927', '10023832872', '10024423030', '10024838291', '10026182328', '10026345258', '10026483183', '10027469678', '10028123364', '10028123716', '10028250952', '10032085493', '10033257247', '10033411435', '10033690581', '10034577697', '10035410291', '10036635494', '1004389199', '10044013493', '10044496971', '1004482610', '10044962660', '10049591718', '10049911701', '10049918427', '1005002367', '10050263201', [... truncated]
Execution halted
Command exited with non-zero status 1
56.19user 0.49system 0:56.82elapsed 99%CPU (0avgtext+0avgdata 939700maxresident)k
25432inputs+0outputs (86major+99816minor)pagefaults 0swaps

How can I change row.names? 

Many thanks, 

Yurany

**Comment by keiranmraine** [comment]
It looks like you have used the old reference files from PanCancer and not the [improved versions](ftp://ftp.sanger.ac.uk/pub/cancer/support-files/CPIB/ascatNgs/Human/GRCh37/) released with the [protocols paper](http://onlinelibrary.wiley.com/doi/10.1002/cpbi.17/full) or indicated via the examples in [dockstore-cgpwgs](https://github.com/cancerit/dockstore-cgpwgs/blob/develop/examples/analysis_config.local.json).

**Comment by andromedia33** [comment]
Dear author,
I'm having exactly the same issue here. I'm actually using a very recent reference for this (hs37d5), and when I downloaded the reference files you indicated, I can see they are exactly the same. Still I'm running into the "duplicate row.names" issue after the alleles were counted.
How can I rectify this please? Thank you very much!
