### ISSUE TITLE
How to output all the solution that ASCATngs found?

### ISSUE THREAD

**Issue by jiaqianwang** [cancerit/ascatNgs#70]
How to output all the solution that ASCATngs found? Now the software only output the best solutions with purity, polidy and copy numbers. However sometimes the solution is not perfect. So how can I output the other solutions?

**Comment by keiranmraine** [comment]
Hi,

ascatNgs has always only produced one result (unlike the underlying R library), you can however prevent cleanup of the workspace with `-noclean` and then re-fit with adjusted purity/ploidy parameters.

You will need to delete some files:

```
rm $OUTPUT/tmpAscat/progress/*ascat*
rm $OUTPUT/tmpAscat/progress/*finalise*
```
