### ISSUE TITLE
setting gender to XY

### ISSUE THREAD

**Issue by lmy06** [cancerit/ascatNgs#73]
Hi, I was using ascatNGS with WGS datas.
     I just find out if I set the gender to XY, the CNV segment result will show a deletion in chrX.
     Even the data is from a female, if I set the gender=XY, there will be a deletion in the chrX.
     And the other chromosomes' CNV segments were different between setting gender to XY or XX.
     I'm wondering why this happens?

**Comment by keiranmraine** [comment]
Issues with the underlying ASCAT algorithm should be raised on their repository detailed in the README.  You should either set gender correctly for the samples or specify gender as 'L' for the code to determine it using Y specific SNP loci.
