### ISSUE TITLE
hg38 Snp GC correction file

### ISSUE THREAD

**Issue by Caninus23** [cancerit/ascatNgs#79]
Is there a possibility to generate such file for hg38?

**Comment by keiranmraine** [comment]
A script is included for this purpose.  Documentation can be found in the wiki:

https://github.com/cancerit/ascatNgs/wiki/Convert-SnpPositions.tsv-to-SnpGcCorrections.tsv

**Comment by keiranmraine** [comment]
As a note for future use, the relevant file is included in this archive available from the Sanger FTP site:

```
ftp://ftp.sanger.ac.uk/pub/cancer/dockstore/human/GRCh38_hla_decoy_ebv/CNV_SV_ref_GRCh38_hla_decoy_ebv_brass6+.tar.gz
```

The file to extract is:

```
CNV_SV_ref_GRCh38_hla_decoy_ebv_brass6+/ascat/SnpGcCorrections.tsv
```

**Comment by umasaxena** [comment]
Hello, is this site update ? If you wouldnt mind could you please send me the current location for the "CNV_SV_ref_GRCh38_hla_decoy_ebv_brass6+/ascat/SnpGcCorrections.tsv" file.

**Comment by keiranmraine** [comment]
The location is unchanged.  Most web-browsers no longer support ftp and you will need to use a dedicated client.

However, the file is also accessible via the http protocol (in web-browser):

```
http://ftp.sanger.ac.uk/pub/cancer/dockstore/human/GRCh38_hla_decoy_ebv/CNV_SV_ref_GRCh38_hla_decoy_ebv_brass6+.tar.gz
```

**Comment by umasaxena** [comment]
Many thanks

**Comment by KathyCat1** [comment]
How to get segment level of copy number like ASCAT for WES,  with chr start- end per copy number                                  
head ascat_out/J78AIS.copynumber.txt
        Chromosome      Position        Log R   segmented LogR  BAF     segmented BAF   Copy number     Minor allele    Raw copy number
rs62635286      1       13116   -1.87555628113731       -0.0605505377127584     0       NA      3       1       0.343360059102869
rs62636497      1       15274   NA      -0.0605505377127584     NA      NA      3       1       NA
rs806731        1       30923   0.692439784204986       -0.0605505377127584     0       NA      3       1       8.73542496544808
rs116400033     1       51479   -0.0667777124781612     -0.0605505377127584     1       NA      3       1       3.3553946036283
rs141149254     1       54490   -0.230861488577514      -0.0605505377127584     0       NA      3       1       2.72857614141887
rs28396308      1       55545   -0.0163521722183716     -0.0605505377127584     1       NA      3       1       3.57555015830608
rs114420996     1       58814   0.228953394000139       -0.0605505377127584     1       NA      3       1       4.87085609998217
rs62637817      1       60351   -0.570543243821012      -0.0605505377127584     0       NA      3       1       1.77835717443695
rs80011619      1       63671   0.316724969560093       -0.0605505377127584     1       NA      3       1       5.44057843492366

**Comment by AndyMenzies** [comment]
Hi

This project is a WGS specific wrapper around ASCAT.  The underlying ASCAT algorithm has been updated to support WES data, although we don't.

Please see - https://github.com/VanLoo-lab/ascat

Andy
