### ISSUE TITLE
Purity and ploidy in CNV analysis

### ISSUE THREAD

**Issue by beginner984** [cancerit/ascatNgs#83]
Thank you for this tool

In copy number analysis from scatngs for each sample I have these outputs

**copynumber.caveman.csv

copynumber.txt

samplestatistics.txt**

Can I use **purity** and **ploidy** mentioned in output picture for example from information in this plot, I really need this information 

![WTSI-OESO_013_a_DNA ASCATprofile](https://user-images.githubusercontent.com/43682980/55496825-d0ee9f00-5637-11e9-9fc5-2e3186e9d2dc.jpg)

Thank you for any help

**Comment by keiranmraine** [comment]
Please see the [wiki](https://github.com/cancerit/ascatNgs/wiki) for details of the protocols paper which covers interpretation of results.

**Comment by beginner984** [comment]
Sorry,

This is a few lines of my copynumber.caveman.csv output


```
1	1	13116	665401	2	1	3	1
2	1	668374	96324627	2	1	2	1
3	1	96326095	96419709	2	1	1	0
4	1	96421112	103508275	2	1	2	1
```

In protocol paper says 


```
copynumber.caveman.csv	Comma-separated values	Simple form of copy number segments in format:

    Segment number

    Chromosome

    Start position (origin-1)

    End position (origin-1)

    Major copy number—normal

    Minor copy number—normal

    Major copy number—tumor

    Minor copy number—tumor
```
But my first column does not seem to be total copy number 

How I can get such information from my file

```
Chromosome	Start	End	Total_CN	Minor_CN
1	10583	1017587	3	1
1	1018144	2466425	5	2
1	2475113	7770901	3	1


[WTSI-OESO_121_1pre.copynumber.caveman.txt](https://github.com/cancerit/ascatNgs/files/3101702/WTSI-OESO_121_1pre.copynumber.caveman.txt)

```

**Comment by RamRS** [comment]
> But my first column does not seem to be total copy number

Because it is not. The protocol paper clearly says (from what you pasted) that the first column is `Segment number`.
