### ISSUE TITLE
Whether ASCAT can be used in target sequencing data ?

### ISSUE THREAD

**Issue by lidd77** [cancerit/ascatNgs#85]
HI,

I have read ASCAT paper ,but I did not find any prompts about whether ASCAT support the input of target sequncing data .

So whether it supports the target sequencing data ??

Best ,

**Comment by keiranmraine** [comment]
ascatNgs only supports WGS (whole genome sequencing) as detailed in the first few lines of the repository readme (which also indicates who to contact for anything else):

https://github.com/cancerit/ascatNgs

(I've updated the description of the project to further emphasise)
