### ISSUE TITLE
Getting the ploidy of tumour

### ISSUE THREAD

**Issue by beginner984** [cancerit/ascatNgs#88]
Hi

The only thing I have is the output of scatngs like below 

```
Chromosome	Start	End	Total_CN	Minor_CN
1	16298	12889922	2	1
1	12890791	13182878	3	1
1	13182899	22208689	2	1
1	22210044	22360814	3	1
1	22361313	31163036	2	1
```

Could I infer tumour ploidy from this data please?

**Comment by keiranmraine** [comment]
You should have a text file `*.samplestatistics.txt`:

```
NormalContamination 0
Ploidy 3.79736096337017
rho 1
psi 3.65
goodnessOfFit 97.9828769860925
GenderChr Y
GenderChrFound Y
```

For additional information see the protocols paper linked from the [wiki](https://github.com/cancerit/ascatNgs/wiki)
