### ISSUE TITLE
Copy number changes of ploidy-gain sample

### ISSUE THREAD

**Issue by wanhui5867** [cancerit/ascatNgs#95]
Hi,

I have several tumor samples that had a ploidy gain (2n -> 4n) comparing to the normal sample. When plotting the Copy number changes, all chromosomes of those tumor samples show color change. (please see below figure:  bottom is copy number of each sample (darkgreen-green-grey-orange-red presents copy number from 0-1-2-3-…)
![image](https://user-images.githubusercontent.com/31027318/86531017-172b5180-bebe-11ea-8f7b-ba77eee5af2b.png)

However, it is strange that all chromosomes have a copy number gain in the tumor cell. Do you have any suggestions about presenting the copy number change of ploidy-gain samples?

**Comment by keiranmraine** [comment]
I recommend you raise this question with the developers of the underlying R package.  We only provide support for the ngs wrapping code and easy execution:

https://github.com/Crick-CancerGenomics/ascat

**Comment by wanhui5867** [comment]
Thanks for your advice! 

I moved my question to the ASCAT R package: https://github.com/Crick-CancerGenomics/ascat/issues/61
